# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yexw/coreCliqueRemoval

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yexw/coreCliqueRemoval

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yexw/coreCliqueRemoval/CMakeFiles /home/yexw/coreCliqueRemoval//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yexw/coreCliqueRemoval/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kcc

# Build rule for target.
kcc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kcc
.PHONY : kcc

# fast build rule for target.
kcc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kcc.dir/build.make CMakeFiles/kcc.dir/build
.PHONY : kcc/fast

#=============================================================================
# Target rules for targets named mce

# Build rule for target.
mce: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mce
.PHONY : mce

# fast build rule for target.
mce/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mce.dir/build.make CMakeFiles/mce.dir/build
.PHONY : mce/fast

#=============================================================================
# Target rules for targets named Graph

# Build rule for target.
Graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Graph
.PHONY : Graph

# fast build rule for target.
Graph/fast:
	$(MAKE) $(MAKESILENT) -f src/graph/CMakeFiles/Graph.dir/build.make src/graph/CMakeFiles/Graph.dir/build
.PHONY : Graph/fast

#=============================================================================
# Target rules for targets named kCListClique

# Build rule for target.
kCListClique: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kCListClique
.PHONY : kCListClique

# fast build rule for target.
kCListClique/fast:
	$(MAKE) $(MAKESILENT) -f src/clique/CMakeFiles/kCListClique.dir/build.make src/clique/CMakeFiles/kCListClique.dir/build
.PHONY : kCListClique/fast

#=============================================================================
# Target rules for targets named MCE

# Build rule for target.
MCE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MCE
.PHONY : MCE

# fast build rule for target.
MCE/fast:
	$(MAKE) $(MAKESILENT) -f src/MClique/CMakeFiles/MCE.dir/build.make src/MClique/CMakeFiles/MCE.dir/build
.PHONY : MCE/fast

src/run/kclistCliqueRunner.o: src/run/kclistCliqueRunner.cpp.o
.PHONY : src/run/kclistCliqueRunner.o

# target to build an object file
src/run/kclistCliqueRunner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kcc.dir/build.make CMakeFiles/kcc.dir/src/run/kclistCliqueRunner.cpp.o
.PHONY : src/run/kclistCliqueRunner.cpp.o

src/run/kclistCliqueRunner.i: src/run/kclistCliqueRunner.cpp.i
.PHONY : src/run/kclistCliqueRunner.i

# target to preprocess a source file
src/run/kclistCliqueRunner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kcc.dir/build.make CMakeFiles/kcc.dir/src/run/kclistCliqueRunner.cpp.i
.PHONY : src/run/kclistCliqueRunner.cpp.i

src/run/kclistCliqueRunner.s: src/run/kclistCliqueRunner.cpp.s
.PHONY : src/run/kclistCliqueRunner.s

# target to generate assembly for a file
src/run/kclistCliqueRunner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kcc.dir/build.make CMakeFiles/kcc.dir/src/run/kclistCliqueRunner.cpp.s
.PHONY : src/run/kclistCliqueRunner.cpp.s

src/run/maximalCliqueLargeClique.o: src/run/maximalCliqueLargeClique.cpp.o
.PHONY : src/run/maximalCliqueLargeClique.o

# target to build an object file
src/run/maximalCliqueLargeClique.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mce.dir/build.make CMakeFiles/mce.dir/src/run/maximalCliqueLargeClique.cpp.o
.PHONY : src/run/maximalCliqueLargeClique.cpp.o

src/run/maximalCliqueLargeClique.i: src/run/maximalCliqueLargeClique.cpp.i
.PHONY : src/run/maximalCliqueLargeClique.i

# target to preprocess a source file
src/run/maximalCliqueLargeClique.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mce.dir/build.make CMakeFiles/mce.dir/src/run/maximalCliqueLargeClique.cpp.i
.PHONY : src/run/maximalCliqueLargeClique.cpp.i

src/run/maximalCliqueLargeClique.s: src/run/maximalCliqueLargeClique.cpp.s
.PHONY : src/run/maximalCliqueLargeClique.s

# target to generate assembly for a file
src/run/maximalCliqueLargeClique.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mce.dir/build.make CMakeFiles/mce.dir/src/run/maximalCliqueLargeClique.cpp.s
.PHONY : src/run/maximalCliqueLargeClique.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Graph"
	@echo "... MCE"
	@echo "... kCListClique"
	@echo "... kcc"
	@echo "... mce"
	@echo "... src/run/kclistCliqueRunner.o"
	@echo "... src/run/kclistCliqueRunner.i"
	@echo "... src/run/kclistCliqueRunner.s"
	@echo "... src/run/maximalCliqueLargeClique.o"
	@echo "... src/run/maximalCliqueLargeClique.i"
	@echo "... src/run/maximalCliqueLargeClique.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

